---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-dx-diy
description: Custom bazzite-dx roll w/ config saves
base-image: ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: 42

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - lukenukem/asus-linux

    install:
      packages:
        - btop
        - curl
        - fd
        - git
        - gh
        - htop
        - neovim
        - nmap
        - openssh
        - ripgrep
        - solaar
        - starship
        - tmux
        - tldr
        - unzip
        - wget
        - zsh

        # Asus specific entries:
        - asusctl                 # ASUS control utility
        - supergfxctl             # Graphics switching daemon

    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)


  - type: default-flatpaks
    configurations:
      - scope: user
        notify: true
        repo:
          title: Flathub (user)
        install: # system flatpaks we want all users to have and not remove
          - app.zen_browser.zen
          - com.bitwarden.desktop
          - com.calibre_ebook.calibre
          - com.discordapp.Discord
          - com.github.PintaProject.Pinta
          - com.moonlight_stream.Moonlight
          - com.protonvpn.www
          - com.rtosta.zapzap
          - com.stremio.Stremio
          - com.vscodium.codium
          - io.appflowy.AppFlowy
          - io.github.pwr_solaar.solaar
          - io.github.softfever.OrcaSlicer
          - org.chromium.Chromium
          - org.mozilla.firefox
          - org.gimp.GIMP
          - org.libreoffice.LibreOffice
          - org.qbittorrent.qBittorrent
          - org.videolan.VLC
          - org.virt_manager.virt-manager
          - org.wezfurlong.wezterm
  - type: signing
