---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-dx-diy
description: Custom bazzite-dx roll w/ config saves
base-image: ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      - usr: /usr  
      - etc: /etc

  - type: repo
    repos:
      - name: lukenukem/asus-linux
        description: Copr repo for asus-linux owned by lukenukem
        baseurl: https://download.copr.fedorainfracloud.org/results/lukenukem/asus-linux/fedora-$releasever-$basearch/
        gpgkey: https://download.copr.fedorainfracloud.org/results/lukenukem/asus-linux/pubkey.gpg

  - type: dnf
    repos:
      copr:
        - atim/starship

    install:
      packages:
        - btop
        - curl
        - fd
        - git
        - gh
        - htop
        - neovim
        - nmap
        - openssh
        - ripgrep
        - solaar
        - starship
        - tmux
        - tldr
        - unzip
        - wget
        - zsh

        # Asus specific entries:
        - asusctl                 # ASUS control utility
        - supergfxctl             # Graphics switching daemon

    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)


  - type: flatpaks
    install:          
    - app.zen_browser.zen
    - com.bitwarden.desktop
    - com.calibre_ebook.calibre
    - com.discordapp.Discord
    - com.github.PintaProject.Pinta
    - com.moonlight_stream.Moonlight
    - com.protonvpn.www
    - com.rtosta.zapzap
    - com.stremio.Stremio
    - com.vscodium.codium
    - io.appflowy.AppFlowy
    - io.github.pwr_solaar.solaar
    - io.github.softfever.OrcaSlicer
    - org.chromium.Chromium
    - org.gimp.GIMP
    - org.libreoffice.LibreOffice
    - org.qbittorrent.qBittorrent
    - org.videolan.VLC
    - org.virt_manager.virt-manager
    - org.wezfurlong.wezterm
  - scope: user # Also add Flathub user repo, but no user packages
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
