---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebuild-diy
description: Aurora DX with open Nvidia drivers and Asus specific updates
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: latest #42 # latest is also supported if you want new updates ASAP

kernel-args:
  - rd.driver.blacklist=nouveau
  - modprobe.blacklist=nouveau
  - nvidia-drm.modeset=1

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        # CachyOS Kernel Has Asus optimizations and some bonus features
        - bieszczaders/kernel-cachyos
        
        - name: lukenukem/asus-linux
          description: Copr repo for asus-linux owned by lukenukem
          baseurl: https://download.copr.fedorainfracloud.org/results/lukenukem/asus-linux/fedora-$releasever-$basearch/
          gpgkey: https://download.copr.fedorainfracloud.org/results/lukenukem/asus-linux/pubkey.gpg


    install:
      packages:
        - btop
        - curl
        - fd
        - git
        - gh
        - htop
        - neovim
        - nmap
        - openssh
        - ripgrep
        - solaar
        - starship
        - tmux
        - tldr
        - unzip
        - wget
        - zsh

        # Asus specific entries:
        - akmod-nvidia            # Core driver package
        - xorg-x11-drv-nvidia-power # Required for power management
        - xorg-x11-drv-nvidia-cuda  # Required for CUDA
        - asusctl                 # ASUS control utility
        - supergfxctl             # Graphics switching daemon
        # Asus Optimized CachyOS Kernal + patches
        - kernel-cachyos
        - kernel-cachyos-core
        - kernel-cachyos-devel
        - kernel-cachyos-modules
        - kernel-cachyos-modules-extra

    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

        # Remove for CachyOS kernel to be applied
        - kernel
        - kernel-core
        - kernel-devel
        - kernel-modules
        - kernel-modules-extra

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - app.zen_browser.zen
          - com.bitwarden.desktop
          - com.calibre_ebook.calibre
          - com.discordapp.Discord
          #- com.freecad.FreeCAD
          - com.github.PintaProject.Pinta
          #- com.inkscape.Inkscape
          - com.moonlight_stream.Moonlight
          #- com.openscad.OpenSCAD
          - com.rtosta.zapzap
          - com.stremio.Stremio
          - com.valvesoftware.Steam
          - com.visualstudio.code
          - org.gimp.GIMP
          - org.gnome.Loupe
          - org.kde.okular
          - org.libreoffice.LibreOffice
          - org.qbittorrent.qBittorrent
          - org.videolan.VLC
          - org.virt_manager.virt-manager 
      - scope: user # Also add Flathub user repo, but no user packages
  - type: akmods
    base: asus # if not specified, classic "main" base is used by default
    install:
      - kvmfr
      - v4l2loopback
      - zenergy
      - ryzen-smu
    #nvidia-driver: nvidia-open

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
